// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-02-14 11:13:00.006583 +0300 +03 m=+4.872470437

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Yengas",
            "email": "yigitcan.ucum@trendyol.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/_monitoring/health": {
            "get": {
                "description": "returns ok if the server is up",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "get status of the server",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/device": {
            "post": {
                "description": "register a new device with the given parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "register a new device",
                "parameters": [
                    {
                        "description": "info of the device to register",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http_device.deviceRegisterRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created new device",
                        "schema": {
                            "$ref": "#/definitions/http_device.deviceRegisterResponseDTO"
                        }
                    },
                    "400": {
                        "description": "invalid request parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "unexpected error occurred",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/metric/temperature": {
            "get": {
                "description": "given a device and a starting date, returns all temperature metrics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metric"
                ],
                "summary": "query temperature metrics of devices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the device",
                        "name": "deviceID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "metrics matching the criteria",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ingestion.DecimalMetricValue"
                            }
                        }
                    },
                    "404": {
                        "description": "no metrics found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "unexpected error occurred",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "inserts temperature metric data for the given device id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metric"
                ],
                "summary": "insert temperature metric data for devices",
                "parameters": [
                    {
                        "description": "metrics to insert",
                        "name": "metrics",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ingestion.DecimalMetricValue"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "inserted the temperature metrics",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "invalid request parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "no device token supplied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "unexpected error occurred",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http_device.deviceRegisterRequestDTO": {
            "type": "object",
            "properties": {
                "firmware_version": {
                    "type": "string",
                    "example": "1.0.0-1"
                },
                "serial_number": {
                    "type": "string",
                    "example": "TEST-123"
                }
            }
        },
        "http_device.deviceRegisterResponseDTO": {
            "type": "object",
            "properties": {
                "device": {
                    "type": "object",
                    "$ref": "#/definitions/registry.Device"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "ingestion.DecimalMetricValue": {
            "type": "object",
            "properties": {
                "time": {
                    "description": "Epoch timestamp in seconds",
                    "type": "integer",
                    "example": 1578859629
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "registry.Device": {
            "type": "object",
            "properties": {
                "firmware_version": {
                    "type": "string",
                    "example": "1.0.0-1"
                },
                "id": {
                    "type": "integer"
                },
                "registration_date": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2017-07-21T17:32:28Z"
                },
                "serial_number": {
                    "type": "string",
                    "example": "TEST-123"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{"http"},
	Title:       "IOT Demo",
	Description: "Devices and Metrics API",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
