default:
  server:
    name: 'iot-demo'
    host: '0.0.0.0'
    port: 8080
  swagger:
    documentation_host: ''
    documentation_base_path: '/'
  auth:
    secret: 'iot-demo-secret'

dev: {}

stage: {}

prod: {}
