// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"iot-demo/adapters/config"
	"iot-demo/adapters/http"
	"iot-demo/adapters/jwt"
	"iot-demo/adapters/storage/memory"
	"iot-demo/pkg/device/add-device"
	"iot-demo/pkg/device/registry"
	"iot-demo/pkg/metrics/add-metrics"
	"iot-demo/pkg/metrics/ingestion"
	"iot-demo/pkg/metrics/query-metrics"
)

// Injectors from wire.go:

func InitializeServer(cs config.Selection) (*http_server.HTTPServer, error) {
	static, err := config.ReadStatic(cs)
	if err != nil {
		return nil, err
	}
	http_serverConfig := NewHTTPServerConfig(static)
	jwtConfig := NewJWTConfig(static)
	authJWT := jwt.NewJWT(jwtConfig)
	deviceJWT := NewDeviceJWT(authJWT)
	memoryRegistry := memory.NewRegistry()
	service := registry.NewService(memoryRegistry)
	add_deviceService := add_device.NewService(service, deviceJWT)
	ingestionDecimal := memory.NewIngestion()
	decimalService := ingestion.NewDecimalService(ingestionDecimal)
	dynamicGetter, err := config.NewDynamicGetter(cs)
	if err != nil {
		return nil, err
	}
	add_metricsService := add_metrics.NewService(decimalService, dynamicGetter)
	query_metricsService := query_metrics.NewService(decimalService)
	handler := http_server.NewHandlers(http_serverConfig, deviceJWT, add_deviceService, add_metricsService, query_metricsService)
	httpServer := http_server.NewServer(http_serverConfig, handler)
	return httpServer, nil
}

// wire.go:

func NewJWTConfig(cfg config.Static) jwt.Config {
	return jwt.Config{Secret: []byte(cfg.Auth.Secret)}
}

func NewDeviceJWT(authJWT jwt.AuthJWT) jwt.DeviceJWT {
	return jwt.DeviceJWT(authJWT)
}

func NewHTTPServerConfig(cfg config.Static) http_server.Config {
	return http_server.Config{
		Host:                  cfg.Server.Host,
		DocumentationHost:     cfg.Swagger.DocumentationHost,
		DocumentationBasePath: cfg.Swagger.DocumentationBasePath,
		Port:                  cfg.Server.Port,
		IsRelease:             cfg.IsRelease,
	}
}

var (
	configSet = wire.NewSet(config.ReadStatic, config.NewDynamicGetter, wire.Bind(new(add_metrics.ConfigGetter), new(*config.DynamicGetter)))
	jwtSet    = wire.NewSet(
		NewJWTConfig, jwt.NewJWT, NewDeviceJWT, wire.Bind(new(http_server.DeviceTokenParser), new(jwt.DeviceJWT)), wire.Bind(new(add_device.Tokenizer), new(jwt.DeviceJWT)),
	)
	storageSet = wire.NewSet(memory.NewIngestion, memory.NewRegistry, wire.Bind(new(registry.Repository), new(*memory.Registry)), wire.Bind(new(ingestion.DecimalRepository), new(*memory.IngestionDecimal)))
	httpSet    = wire.NewSet(
		NewHTTPServerConfig, http_server.NewHandlers, http_server.NewServer,
	)
	deviceSet       = wire.NewSet(registry.NewService, wire.Bind(new(add_device.Registerer), new(*registry.Service)))
	ingestionSet    = wire.NewSet(ingestion.NewDecimalService, wire.Bind(new(add_metrics.Inserter), new(*ingestion.DecimalService)), wire.Bind(new(query_metrics.Querier), new(*ingestion.DecimalService)))
	addDeviceSet    = wire.NewSet(add_device.NewService)
	addMetricsSet   = wire.NewSet(add_metrics.NewService)
	queryMetricsSet = wire.NewSet(query_metrics.NewService)
)
